# Command is some binary installed on the underlying container.
# It's up to the lexicon author to ensure these commands are available by configuring the container in the dockerfile.

endpoints:
  parse-project:
    command: php                          # Call "PHP" on the container's command line.
    args:
      - '/server/parse-project.php'       # The PHP parser that will be executed.
      - '${trunkKey}'                     # A string used to ID the topmost node; the parser will increment this internally on new nodes.
      - '${resourceDir}'                  # A filepath of the directory to parse.
  changed-files:
    command: php
    args:
      - '/server/parse-project.php'
      - '${trunkKey}'
      - '${resourceDir}'
      - '${changedFiles}'                 # A list of filepaths relative to ${resourceDir} that will be parsed instead of the whole directory.
                                          # has to be last arg as it will be a list ie. a.php b.php dir/c.php
  list-facts:
    command: cat
    args:
      - '/server/list-facts.json'
  list-setup-steps:
    command: cat
    args:
      - '/server//setup-steps.json'
  replace-properties:
    command: php
    args:
      - '/server/replace-properties.php'
      - '${fact}'                         # The fact to replace properties for
